Repository team-grinder/grinder, pull requests merged in 2024-05, with the labels that each got.

#31 Design: 관리자 페이지 화면 작성
  src/main/resources/static/css/admin.css
  src/main/resources/templates/admin.html
Labels: design

#27 Design: 계정 찾기 화면 작성
  src/main/resources/static/css/findAccountFinishForm.css
  src/main/resources/static/css/findAccountForm.css
  src/main/resources/static/css/welcomeForm.css
  src/main/resources/static/img/icon/BsFillKeyFill.png
  src/main/resources/templates/findAccountFinishForm.html
  src/main/resources/templates/findAccountForm.html
  src/main/resources/templates/welcomeForm.html
Labels: design

#29 Design: 판매자 신청 화면 작성
  src/main/resources/static/css/sellerApplicationForm.css
  src/main/resources/templates/sellerApplicationForm.html
Labels: design

#30 Design: 카페 추가 화면 작성
  src/main/resources/static/css/addCafeForm.css
  src/main/resources/templates/addCafeForm.html
Labels: design

#33 feat : 마이페이지 관련 Repository 추가
  build.gradle
  src/main/java/com/grinder/repository/BlacklistRepository.java
  src/main/java/com/grinder/repository/BookmarkRepository.java
  src/main/java/com/grinder/repository/CafeRegisterRepository.java
  src/main/java/com/grinder/repository/FollowRepository.java
  src/main/resources/db/migration/init.sql
  src/test/java/com/grinder/repository/BlacklistRepositoryTest.java
  src/test/java/com/grinder/repository/BookmarkRepositoryTest.java
  src/test/java/com/grinder/repository/CafeRegisterRepositoryTest.java
  src/test/java/com/grinder/repository/CafeRepositoryTest.java
  src/test/java/com/grinder/repository/FollowRepositoryTest.java
  src/test/java/com/grinder/repository/MemberRepositoryTest.java
Labels: enhancement

#34 Feat : Feed에 필요한 Repository, Service, DTO 추가
  src/main/java/com/grinder/controller/FeedController.java
  src/main/java/com/grinder/domain/dto/FeedDTO.java
  src/main/java/com/grinder/domain/entity/Feed.java
  src/main/java/com/grinder/repository/FeedRepository.java
  src/main/java/com/grinder/repository/ImageRepository.java
  src/main/java/com/grinder/repository/TagRepository.java
  src/main/java/com/grinder/service/FeedService.java
  src/main/java/com/grinder/service/ImageService.java
  src/main/java/com/grinder/service/TagService.java
Labels: enhancement

#32 Design: 피드 작성 화면
  src/main/resources/static/css/feedWriteForm.css
  src/main/resources/static/img/icon/BsLightbulbFill.png
  src/main/resources/static/js/feedWriteForm.js
  src/main/resources/templates/feedWriteForm.html
Labels: design

#36 feat : 차단(블랙리스트) API 구현
  src/main/java/com/grinder/controller/ExControllerAdvice.java
  src/main/java/com/grinder/controller/ExRestControllerAdvice.java
  src/main/java/com/grinder/controller/entity/BlacklistController.java
  src/main/java/com/grinder/domain/dto/BlacklistDTO.java
  src/main/java/com/grinder/exception/HasNotBeenAddedException.java
  src/main/java/com/grinder/exception/LoginRequiredException.java
  src/main/java/com/grinder/exception/MaximumRangeAlreadyAddedException.java
  src/main/java/com/grinder/repository/BlacklistRepository.java
  src/main/java/com/grinder/repository/ImageRepository.java
  src/main/java/com/grinder/repository/MemberRepository.java
  src/main/java/com/grinder/repository/queries/BlacklistQueryRepository.java
  src/main/java/com/grinder/service/BlacklistService.java
  src/main/java/com/grinder/service/implement/BlacklistServiceImpl.java
  src/main/resources/templates/components/header.html
  src/test/java/com/grinder/controller/entity/BlacklistControllerTest.java
  src/test/java/com/grinder/repository/BookmarkRepositoryTest.java
  src/test/java/com/grinder/repository/CafeRegisterRepositoryTest.java
  src/test/java/com/grinder/repository/FollowRepositoryTest.java
  src/test/java/com/grinder/service/BlacklistServiceImplTest.java
Labels: enhancement

#37 Feat: 회원 관리 api 작성
  src/main/java/com/grinder/controller/ExRestControllerAdvice.java
  src/main/java/com/grinder/controller/MemberController.java
  src/main/java/com/grinder/controller/ReportController.java
  src/main/java/com/grinder/controller/SellerApplyController.java
  src/main/java/com/grinder/controller/SellerInfoController.java
  src/main/java/com/grinder/domain/dto/MemberDTO.java
  src/main/java/com/grinder/domain/dto/ReportDTO.java
  src/main/java/com/grinder/domain/dto/SellerApplyDTO.java
  src/main/java/com/grinder/domain/dto/SellerInfoDTO.java
  src/main/java/com/grinder/domain/entity/Member.java
  src/main/java/com/grinder/domain/enums/ContentType.java
  src/main/java/com/grinder/domain/enums/MenuType.java
  src/main/java/com/grinder/domain/enums/Role.java
  src/main/java/com/grinder/domain/enums/TagName.java
  src/main/java/com/grinder/domain/enums/Weekday.java
  src/main/java/com/grinder/repository/MemberRepository.java
  src/main/java/com/grinder/repository/ReportRepository.java
  src/main/java/com/grinder/repository/SellerApplyRepository.java
  src/main/java/com/grinder/repository/SellerInfoRepository.java
  src/main/java/com/grinder/service/MemberService.java
  src/main/java/com/grinder/service/ReportService.java
  src/main/java/com/grinder/service/SellerApplyService.java
  src/main/java/com/grinder/service/SellerInfoService.java
  src/main/java/com/grinder/service/implement/MemberServiceImpl.java
  src/main/java/com/grinder/service/implement/ReportServiceImpl.java
  src/main/java/com/grinder/service/implement/SellerApplyServiceImpl.java
  src/main/java/com/grinder/service/implement/SellerInfoServiceImpl.java
  src/test/java/com/grinder/controller/MemberControllerTest.java
  src/test/java/com/grinder/repository/MemberRepositoryTest.java
  src/test/java/com/grinder/repository/ReportRepositoryTest.java
  src/test/java/com/grinder/service/MemberServiceTest.java
  src/test/java/com/grinder/service/ReportServiceTest.java
  src/test/java/com/grinder/service/SellerApplyServiceTest.java
Labels: enhancement

#39 feat : 북마크 API 구현
  src/main/java/com/grinder/controller/entity/BookmarkController.java
  src/main/java/com/grinder/domain/dto/BookmarkDTO.java
  src/main/java/com/grinder/domain/entity/Cafe.java
  src/main/java/com/grinder/repository/BookmarkRepository.java
  src/main/java/com/grinder/repository/queries/BookmarkQueryRepository.java
  src/main/java/com/grinder/service/BookmarkService.java
  src/main/java/com/grinder/service/implement/BookmarkServiceImpl.java
  src/main/resources/static/img/background.png
  src/main/resources/templates/index.html
  src/test/java/com/grinder/controller/entity/BookmarkControllerTest.java
  src/test/java/com/grinder/service/implement/BlacklistServiceImplTest.java
  src/test/java/com/grinder/service/implement/BookmarkServiceImplTest.java
Labels: enhancement

#45 feat : Alan API 구현
  build.gradle
  src/main/java/com/grinder/controller/entity/CafeSummaryController.java
  src/main/java/com/grinder/domain/dto/AlanDTO.java
  src/main/java/com/grinder/domain/dto/CafeSummaryDTO.java
  src/main/java/com/grinder/domain/entity/CafeSummary.java
  src/main/java/com/grinder/repository/CafeSummaryRepository.java
  src/main/java/com/grinder/service/AlanQuestionService.java
  src/main/java/com/grinder/service/CafeSummaryService.java
  src/main/java/com/grinder/service/implement/AlanQuestionServiceImpl.java
  src/main/java/com/grinder/service/implement/CafeSummaryServiceImpl.java
  src/main/java/com/grinder/utils/AlanAPI.java
  src/main/resources/application-test.properties
  src/test/java/com/grinder/service/implement/CafeSummaryServiceImplTest.java
Labels: enhancement

#47 HOTFIX : build.gradle 오류 해결
  build.gradle
Labels: bug

#49 Feat : 검색 쿼리 작성
  src/main/java/com/grinder/GrinderApplication.java
  src/main/java/com/grinder/config/SchedulingConfig.java
  src/main/java/com/grinder/domain/dto/FeedDTO.java
  src/main/java/com/grinder/domain/entity/Feed.java
  src/main/java/com/grinder/repository/queries/SearchQueryRepository.java
  src/main/java/com/grinder/service/SchedulerService.java
  src/main/java/com/grinder/service/implement/SchedulerServiceImpl.java
Labels: enhancement

#51 Feat : header 호출 작성 및 검색 쿼리 수정
  src/main/java/com/grinder/controller/view/ComponentsController.java
  src/main/java/com/grinder/repository/queries/SearchQueryRepository.java
  src/main/resources/static/js/index.js
  src/main/resources/templates/components/footer.html
  src/main/resources/templates/components/header.html
  src/main/resources/templates/index.html
Labels: enhancement

#50 Fix: 테스트코드 수정
  src/test/java/com/grinder/repository/ReportRepositoryTest.java
  src/test/java/com/grinder/repository/SellerApplyRepositoryTest.java
  src/test/java/com/grinder/service/implement/CafeRegisterServiceImplTest.java
  src/test/java/com/grinder/service/implement/MemberServiceImplTest.java
  src/test/java/com/grinder/service/implement/ReportServiceImplTest.java
  src/test/java/com/grinder/service/implement/SellerApplyServiceImplTest.java
Labels: 💯test

#52 Test : 피드 테스트
  src/main/java/com/grinder/controller/entity/FeedController.java
  src/main/java/com/grinder/domain/dto/CommentDTO.java
  src/main/java/com/grinder/service/CommentService.java
  src/main/java/com/grinder/service/FeedService.java
  src/main/java/com/grinder/service/implement/HeartServiceImpl.java
  src/test/java/com/grinder/service/implement/FeedServiceImplTest.java
Labels: 💯test

#53 Test : 댓글 테스트
  src/test/java/com/grinder/service/implement/CommentServiceImplTest.java
Labels: 💯test

#57 Feat : 마이페이지 팔로우,블랙리스트 호출 작성
  src/main/java/com/grinder/controller/view/ComponentsController.java
  src/main/java/com/grinder/controller/view/MyPageController.java
  src/main/java/com/grinder/domain/dto/FollowDTO.java
  src/main/java/com/grinder/domain/dto/MemberDTO.java
  src/main/java/com/grinder/repository/queries/FollowQueryRepository.java
  src/main/java/com/grinder/repository/queries/SearchQueryRepository.java
  src/main/java/com/grinder/service/MemberService.java
  src/main/java/com/grinder/service/implement/FollowServiceImpl.java
  src/main/java/com/grinder/service/implement/MemberServiceImpl.java
  src/main/resources/db/migration/init.sql
  src/main/resources/static/css/follower.css
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/loginForm.css
  src/main/resources/static/css/myPage.css
  src/main/resources/static/js/header.js
  src/main/resources/static/js/myPage.js
  src/main/resources/templates/components/blacklist.html
  src/main/resources/templates/components/followerList.html
  src/main/resources/templates/components/footer.html
  src/main/resources/templates/components/header.html
  src/main/resources/templates/error.html
  src/main/resources/templates/index.html
  src/main/resources/templates/myPage.html
  src/test/java/com/grinder/controller/entity/FollowControllerTest.java
  src/test/java/com/grinder/service/implement/FollowServiceImplTest.java
Labels: ✨enhancement

#60 Feat : Feed 백/프론트 연결
  src/main/java/com/grinder/controller/view/ComponentsController.java
  src/main/java/com/grinder/domain/dto/CommentDTO.java
  src/main/java/com/grinder/domain/dto/FeedDTO.java
  src/main/resources/dummy.sql
  src/main/resources/static/css/feed.css
  src/main/resources/static/js/cafeCard.js
  src/main/resources/static/js/feed.js
  src/main/resources/templates/components/cafeCard.html
  src/main/resources/templates/components/feed.html
  src/main/resources/templates/index.html
Labels: ✨enhancement

#67 Design: 카페 정보 컴포넌트 작성
  src/main/java/com/grinder/security/handler/APILoginSuccessHandler.java
  src/main/resources/application-prod.properties
  src/main/resources/static/css/updateCafeInfo.css
  src/main/resources/static/js/attachImage.js
  src/main/resources/templates/updateCafeInfo.html
Labels: 🎨design

#79 Feat : 토큰 에러 수정, 오픈시간 수정 로직 작성 및 프론트 연동, 카페 메뉴 불러오기 로직 및 연동
  src/main/java/com/grinder/controller/entity/OpeningHoursController.java
  src/main/java/com/grinder/controller/view/ComponentsController.java
  src/main/java/com/grinder/domain/dto/MenuDTO.java
  src/main/java/com/grinder/domain/dto/OpeningHoursDTO.java
  src/main/java/com/grinder/domain/entity/Feed.java
  src/main/java/com/grinder/domain/entity/Heart.java
  src/main/java/com/grinder/domain/entity/Image.java
  src/main/java/com/grinder/domain/entity/Member.java
  src/main/java/com/grinder/domain/entity/Menu.java
  src/main/java/com/grinder/domain/entity/OpeningHours.java
  src/main/java/com/grinder/domain/entity/Report.java
  src/main/java/com/grinder/domain/entity/Tag.java
  src/main/java/com/grinder/repository/MenuRepository.java
  src/main/java/com/grinder/repository/OpeningHoursRepository.java
  src/main/java/com/grinder/repository/SellerInfoRepository.java
  src/main/java/com/grinder/repository/queries/MenuQueryRepository.java
  src/main/java/com/grinder/security/filter/APILogoutFilter.java
  src/main/java/com/grinder/security/filter/RefreshTokenFilter.java
  src/main/java/com/grinder/security/filter/TokenCheckFilter.java
  src/main/java/com/grinder/service/MyMenuService.java
  src/main/java/com/grinder/service/OpeningHoursService.java
  src/main/java/com/grinder/service/implement/MyMenuServiceImpl.java
  src/main/java/com/grinder/service/implement/OpeningHoursServiceImpl.java
  src/main/resources/static/css/MyMenuCard.css
  src/main/resources/static/css/addCafeForm.css
  src/main/resources/static/css/addMemberForm.css
  src/main/resources/static/css/findAccountFinishForm.css
  src/main/resources/static/css/loginForm.css
  src/main/resources/static/css/welcomeForm.css
  src/main/resources/static/img/Alan_backGround.png
  src/main/resources/static/js/index.js
  src/main/resources/static/js/myCafePage.js
  src/main/resources/static/js/myPage.js
  src/main/resources/templates/components/header.html
  src/main/resources/templates/components/myCafeMenu.html
  src/main/resources/templates/components/updateCafeInfo.html
  src/main/resources/templates/findAccountFinishForm.html
  src/main/resources/templates/index.html
  src/main/resources/templates/myCafePage.html
  src/main/resources/templates/welcomeForm.html
Labels: 🐞bug, ✨enhancement, 🎨design

#80 Feet : 피드 수정/등록 페이지 중간점검
  src/main/java/com/grinder/controller/view/NewFeedController.java
  src/main/java/com/grinder/domain/dto/FeedDTO.java
  src/main/java/com/grinder/domain/entity/Feed.java
  src/main/java/com/grinder/domain/enums/TagName.java
  src/main/java/com/grinder/repository/CafeRepository.java
  src/main/java/com/grinder/repository/queries/SearchQueryRepository.java
  src/main/java/com/grinder/service/CafeService.java
  src/main/java/com/grinder/service/implement/CafeServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/static/css/addCafeForm.css
  src/main/resources/static/css/addMemberForm.css
  src/main/resources/static/css/common.css
  src/main/resources/static/css/feed.css
  src/main/resources/static/css/feedWriteForm.css
  src/main/resources/static/js/feed.js
  src/main/resources/static/js/feedWriteForm.js
  src/main/resources/templates/addMemberForm.html
  src/main/resources/templates/components/feed.html
  src/main/resources/templates/feedWriteForm.html
  src/main/resources/templates/index.html
  src/test/java/com/grinder/repository/SellerApplyRepositoryTest.java
  src/test/java/com/grinder/service/implement/CommentServiceImplTest.java
  src/test/java/com/grinder/service/implement/FeedServiceImplTest.java
Labels: ✨enhancement, 🎨design

#84 Feat : 카페 메뉴 추가 기능 구현 및 연동 확인
  src/main/java/com/grinder/controller/entity/MenuController.java
  src/main/java/com/grinder/controller/view/ComponentsController.java
  src/main/java/com/grinder/domain/dto/MenuDTO.java
  src/main/java/com/grinder/domain/enums/MenuType.java
  src/main/java/com/grinder/repository/queries/FollowQueryRepository.java
  src/main/java/com/grinder/service/MenuService.java
  src/main/java/com/grinder/service/implement/MenuServiceImpl.java
  src/main/resources/static/css/MyMenuCard.css
  src/main/resources/static/css/follower.css
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/menuInfo.css
  src/main/resources/static/css/myCafePage.css
  src/main/resources/static/css/myPage.css
  src/main/resources/static/css/updateCafeInfo.css
  src/main/resources/static/js/myCafePage.js
  src/main/resources/static/js/myPage.js
  src/main/resources/templates/components/blacklist.html
  src/main/resources/templates/components/bookmark.html
  src/main/resources/templates/components/followerList.html
  src/main/resources/templates/components/menuInfo.html
  src/main/resources/templates/menuInfo.html
  src/main/resources/templates/myCafePage.html
  src/main/resources/templates/myPage.html
Labels: ✨enhancement

#88 Feat : 피드, 카페 쿼리 수정, 마이페이지, 카페관리 페이지 연동
  src/main/java/com/grinder/controller/view/ComponentsController.java
  src/main/java/com/grinder/domain/dto/CafeDTO.java
  src/main/java/com/grinder/domain/dto/CommentDTO.java
  src/main/java/com/grinder/domain/dto/FeedDTO.java
  src/main/java/com/grinder/domain/entity/Feed.java
  src/main/java/com/grinder/domain/enums/TagName.java
  src/main/java/com/grinder/repository/queries/CafeQueryRepository.java
  src/main/java/com/grinder/repository/queries/FeedQueryRepository.java
  src/main/java/com/grinder/service/FeedService.java
  src/main/java/com/grinder/service/implement/FeedServiceImpl.java
  src/main/resources/static/css/header.css
  src/main/resources/static/js/cafeFeed.js
  src/main/resources/static/js/header.js
  src/main/resources/static/js/index.js
  src/main/resources/static/js/myCafePage.js
  src/main/resources/static/js/myFeed.js
  src/main/resources/static/js/myPage.js
  src/main/resources/templates/addCafeForm.html
  src/main/resources/templates/addMemberForm.html
  src/main/resources/templates/admin.html
  src/main/resources/templates/cafeInfo.html
  src/main/resources/templates/components/blacklist.html
  src/main/resources/templates/components/bookmark.html
  src/main/resources/templates/components/followerList.html
  src/main/resources/templates/components/myCafeList.html
  src/main/resources/templates/components/myCafeMenu.html
  src/main/resources/templates/components/updateCafeInfo.html
  src/main/resources/templates/findAccountFinishForm.html
  src/main/resources/templates/findAccountForm.html
  src/main/resources/templates/index.html
  src/main/resources/templates/loginForm.html
  src/main/resources/templates/myCafePage.html
  src/main/resources/templates/myImageUpdate.html
  src/main/resources/templates/myPage.html
  src/main/resources/templates/sellerApplicationForm.html
  src/main/resources/templates/welcomeForm.html
Labels: ✨enhancement

#89 Feat : 팔로우 기능 추가
  src/main/java/com/grinder/controller/ExControllerAdvice.java
  src/main/java/com/grinder/controller/view/MyPageController.java
  src/main/java/com/grinder/domain/dto/FollowDTO.java
  src/main/java/com/grinder/repository/FollowRepository.java
  src/main/java/com/grinder/service/FollowService.java
  src/main/java/com/grinder/service/implement/FollowServiceImpl.java
  src/main/resources/static/css/follower.css
  src/main/resources/static/css/myPage.css
  src/main/resources/static/js/myPage.js
  src/main/resources/templates/components/followerList.html
  src/main/resources/templates/myPage.html
Labels: ✨enhancement

#95 Feat : 마이페이지 수정 기능 추가 및 연동 확인
  src/main/java/com/grinder/controller/ExControllerAdvice.java
  src/main/java/com/grinder/controller/entity/MemberController.java
  src/main/java/com/grinder/controller/view/AccountPageController.java
  src/main/java/com/grinder/domain/dto/MemberDTO.java
  src/main/java/com/grinder/repository/MemberRepository.java
  src/main/java/com/grinder/service/MemberService.java
  src/main/java/com/grinder/service/implement/MemberServiceImpl.java
  src/main/resources/static/css/addCafeForm.css
  src/main/resources/static/css/addMemberForm.css
  src/main/resources/static/css/findAccountFinishForm.css
  src/main/resources/static/css/findAccountForm.css
  src/main/resources/static/css/loginForm.css
  src/main/resources/static/css/sellerApplicationForm.css
  src/main/resources/static/css/welcomeForm.css
  src/main/resources/static/js/updateMemberForm.js
  src/main/resources/templates/loginForm.html
  src/main/resources/templates/myPage.html
  src/main/resources/templates/updateMemberForm.html
Labels: ✨enhancement

#96 Feat : 피드 슬라이스 기능 추가
  src/main/java/com/grinder/controller/view/ComponentsController.java
  src/main/java/com/grinder/repository/queries/FeedQueryRepository.java
  src/main/java/com/grinder/service/FeedService.java
  src/main/java/com/grinder/service/implement/FeedServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/static/css/feed.css
  src/main/resources/static/js/feed.js
  src/main/resources/templates/components/feed2.html
  src/main/resources/templates/index.html
Labels: ✨enhancement, 🎨design

#99 Feat : 카페 피드 더보기 에러 쿼리 수정
  src/main/java/com/grinder/controller/ExControllerAdvice.java
  src/main/java/com/grinder/controller/view/ComponentsController.java
  src/main/java/com/grinder/exception/NoMoreContentException.java
  src/main/java/com/grinder/repository/queries/FeedQueryRepository.java
  src/main/resources/static/css/feed.css
  src/main/resources/static/css/myPage.css
  src/main/resources/static/js/cafeFeed.js
  src/main/resources/static/js/feed.js
  src/main/resources/static/js/myFeed.js
  src/main/resources/templates/myCafePage.html
  src/main/resources/templates/myPage.html
Labels: ✨enhancement

#103 Feat : Alan 추천 기능 추가 및 프론트 연동 확인
  src/main/java/com/grinder/controller/ExControllerAdvice.java
  src/main/java/com/grinder/controller/entity/AnalysisTagController.java
  src/main/java/com/grinder/controller/view/ComponentsController.java
  src/main/java/com/grinder/domain/entity/AnalysisTag.java
  src/main/java/com/grinder/domain/entity/Image.java
  src/main/java/com/grinder/domain/entity/Message.java
  src/main/java/com/grinder/domain/entity/Report.java
  src/main/java/com/grinder/exception/RecentAddedTagException.java
  src/main/java/com/grinder/repository/AnalysisTagRepository.java
  src/main/java/com/grinder/repository/MemberRepository.java
  src/main/java/com/grinder/repository/MessageRepository.java
  src/main/java/com/grinder/repository/queries/AnalysisTagQueryRepository.java
  src/main/java/com/grinder/repository/queries/MessageQueryRepository.java
  src/main/java/com/grinder/service/AlanQuestionService.java
  src/main/java/com/grinder/service/AnalysisTagService.java
  src/main/java/com/grinder/service/MessageService.java
  src/main/java/com/grinder/service/implement/AlanQuestionServiceImpl.java
  src/main/java/com/grinder/service/implement/AnalysisTagServiceImpl.java
  src/main/java/com/grinder/service/implement/MessageServiceImpl.java
  src/main/java/com/grinder/service/implement/SchedulerServiceImpl.java
  src/main/java/com/grinder/utils/AlanAPI.java
  src/main/resources/static/css/header.css
  src/main/resources/static/css/index.css
  src/main/resources/static/img/Alan.png
  src/main/resources/static/js/index.js
  src/main/resources/static/js/myFeed.js
  src/main/resources/templates/components/alanTab.html
  src/main/resources/templates/components/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/myPage.html
Labels: ✨enhancement

#106 Feat : 피드 이미지 모달창 추가
  src/main/resources/data.sql
  src/main/resources/static/css/feed.css
  src/main/resources/static/js/feed.js
  src/main/resources/static/js/feedWriteForm.js
  src/main/resources/templates/components/feed.html
Labels: ✨enhancement

#108 docs : Readme 추가
  README.md
  readme/Alan cafe Summary.png
  readme/ERD.png
  readme/RequestForProposal.png
  readme/System.png
  readme/admin.png
  readme/alan_recommend.png
  readme/bookmark.png
  readme/cafeInfoMenu.png
  readme/cafeInfoPage.png
  readme/changefinish.png
  readme/feedadd.png
  readme/findpassword.png
  readme/follow.png
  readme/grinder_banner.png
  readme/jira.png
  readme/login.png
  readme/main(guest).png
  readme/main.png
  readme/member1.png
  readme/member2.png
  readme/member3.png
  readme/member4.png
  readme/member5.png
  readme/member6.png
  readme/mindmap.png
  readme/myCafe.png
  readme/myCafeList.png
  readme/myCafemenu.png
  readme/myPage.png
  readme/signup.png
  readme/signupfinish.png
  readme/updatemember.png
  src/main/resources/templates/components/header.html
Labels: documentation

#110 docs : Readme 추가
  README.md
  readme/GuestMain.png
  readme/Postgres.png
  readme/member10.png
  readme/member7.png
  readme/member8.png
  readme/member9.png
  readme/memberMain.png
  src/main/resources/static/js/index.js
Labels: documentation

#114 Feat : 피드 생성 버튼 추가
  src/main/java/com/grinder/controller/entity/CafeController.java
  src/main/java/com/grinder/controller/view/ComponentsController.java
  src/main/resources/static/css/common.css
  src/main/resources/static/css/feed.css
  src/main/resources/static/img/feed-create-btn.png
  src/main/resources/static/js/feedWriteForm.js
  src/main/resources/templates/components/feed.html
  src/main/resources/templates/index.html
Labels: ✨enhancement

#117 feat : 피드 추천 쿼리, 단일 호출 쿼리 작성, 스케줄링 추가
  src/main/java/com/grinder/controller/entity/CommentController.java
  src/main/java/com/grinder/controller/entity/FeedController.java
  src/main/java/com/grinder/controller/entity/HeartController.java
  src/main/java/com/grinder/controller/view/ComponentsController.java
  src/main/java/com/grinder/repository/CommentRepository.java
  src/main/java/com/grinder/repository/FeedRepository.java
  src/main/java/com/grinder/repository/HeartRepository.java
  src/main/java/com/grinder/repository/queries/FeedQueryRepository.java
  src/main/java/com/grinder/service/FeedService.java
  src/main/java/com/grinder/service/implement/FeedServiceImpl.java
  src/main/java/com/grinder/service/implement/SchedulerServiceImpl.java
  src/main/resources/static/css/cafeInfo.css
  src/main/resources/static/css/myCafePage.css
  src/main/resources/templates/cafeInfo.html
  src/main/resources/templates/search.html
Labels: ✨enhancement

#121 Fix : 피드 자잘한 수정
  src/main/java/com/grinder/controller/entity/CafeController.java
  src/main/java/com/grinder/controller/view/ComponentsController.java
  src/main/resources/static/css/myPage.css
  src/main/resources/static/js/feed.js
  src/main/resources/static/js/feedWriteForm.js
  src/main/resources/templates/components/feed.html
  src/main/resources/templates/myPage.html
Labels: 🛠️fix

#144 feat : 스케줄러 배치 시스템 구현
  build.gradle
  src/main/java/com/grinder/GrinderApplication.java
  src/main/java/com/grinder/config/BatchConfig.java
  src/main/java/com/grinder/domain/entity/SchedulerLog.java
  src/main/java/com/grinder/repository/SchedulerLogRepository.java
  src/main/java/com/grinder/repository/queries/FeedQueryRepository.java
  src/main/java/com/grinder/security/handler/APILoginSuccessHandler.java
  src/main/java/com/grinder/service/SchedulerService.java
  src/main/java/com/grinder/service/implement/SchedulerServiceImpl.java
  src/main/resources/static/js/myPage.js
  src/main/resources/templates/components/cafeCard.html
  src/main/resources/templates/components/myCafeList.html
  src/test/java/com/grinder/GrinderApplicationTests.java
Labels: ✨enhancement

#148 Test : 테스트 코드 추가
  README.md
  src/main/java/com/grinder/domain/entity/SchedulerLog.java
  src/main/java/com/grinder/repository/queries/AnalysisTagQueryRepository.java
  src/main/java/com/grinder/repository/queries/CafeQueryRepository.java
  src/main/java/com/grinder/repository/queries/FeedQueryRepository.java
  src/test/java/com/grinder/config/TestConfig.java
  src/test/java/com/grinder/repository/queries/AnalysisTagQueryRepositoryTest.java
  src/test/java/com/grinder/repository/queries/BlacklistQueryRepositoryTest.java
  src/test/java/com/grinder/repository/queries/BookmarkQueryRepositoryTest.java
  src/test/java/com/grinder/repository/queries/CafeQueryRepositoryTest.java
  src/test/java/com/grinder/repository/queries/CommentQueryRepositoryTest.java
  src/test/java/com/grinder/security/filter/APILoginFilterTest.java
Labels: 💯test
